@startuml

legend right
  | Cor | Tipo |
  |<#9AC2C5>| Framework - Frozen Spot |
  |<#ffe66d>| Framework - Hot Spot|
  |<#E9E9E9>| Instância |
endlegend

package models {
    class models.Model <<DAO>> {
        + save()
        + delete()
        + objects: Manager
    }
}

package forecast {
    abstract class ModeloDePrevisao #ffe66d {
        # nome_modelo: String
        # parametros: Dict
        + processar(entrada): Any
        
        + data_lake: DataLake
    }

    class ModeloDePrevisaoImagem #9AC2C5 {
        + processar(entrada: Dict): int
    }

    ModeloDePrevisaoImagem --|> ModeloDePrevisao

    class ModeloDePrevisaoSerie #9AC2C5 {
        + processar(entrada: Dict): int
    }

    ModeloDePrevisaoSerie --|> ModeloDePrevisao

    class FactoryModeloDePrevisao {
        + gerar_modelo(nome_modelo: String, parametros: Dict): ModeloDePrevisao
    }

    FactoryModeloDePrevisao ..> ModeloDePrevisao : cria
    
}

package core {
    abstract class Observer #ffe66d {
        + subject : Any
        + update(): void
    }

    class LocalObserver #9AC2C5{
        + subject: Any
        + update(): void
    }

    LocalObserver --|> Observer

    abstract class DataLake <<DAO>> #ffe66d {
        - db: DataLake
        + getInstance(): DataLake
    }

    DataLake --> DataLake : retorna
    
    class MongoAccess #9AC2C5{
        - db: MongoAccess
        + getInstance(): MongoAccess
        + getSeries(series_id: int): list
    }
    
    MongoAccess --|> core.DataLake

    class Usuario {
        + user: OneToOneField<User>
        + locais_favoritos: ManyToManyField<Local>
        + save()
        + delete()
        + objects
    }

    Usuario --|> models.Model
    Usuario "0..*" --> "0..*" Local : salva

    class Local {
        - inscritos: List<Usuario>
        - estado: int
        + attach()
        + nome: String
        + latitude: Decimal
        + longitude: Decimal
        + avisos: ManyToManyField<Aviso>
        + informacoes: ManyToManyField<Informacao>
        + estimar(modelo: ModeloDePrevisao): Any
        + save()
        + delete()
        + objects
    }

    Local --|> models.Model
    Local "1" --> "0..*" Aviso : possui
    Local "1" --> "0..*" Informacao : possui
    Local ..> ModeloDePrevisao : utiliza
    Local ..> LocalObserver : utiliza

    class Previsao {
        + data: DateField
        + hora: TimeField
        + estimativa_pessoas: PositiveInteger
        + modelo: String
        + local: ForeignKey<Local>
        + save()
        + delete()
        + objects
    }

    Previsao --|> models.Model
    Previsao "0..*" --> "1" Local : pertence

    class Aviso {
        + descricao: Text
        + tipo: String
        + fonte: String
        + data: DateField
        + save()
        + delete()
        + objects
    }

    Aviso --|> models.Model

    class Informacao {
        + tipo: String
        + descricao: Text
        + imagem: ImageField
        + usuario: ForeignKey<Usuario>
        + save()
        + delete()
        + objects
    }

    Informacao --|> models.Model
    Informacao "0..*" --> "1" Usuario : enviada_por
    
    forecast.ModeloDePrevisao ..> MongoAccess : utiliza
}

@enduml
